
SELECT B.ID, B.NAME, SUM(A.AMOUNT)
FROM WH_INFLOWS A
INNER JOIN PRODUCTS B ON A.PRODUCT = B.ID
GROUP BY B.ID, B.NAME
ORDER BY B.ID;

SELECT A.WAREHOUSE, D.NAME, B.ID, B.NAME, SUM(A.AMOUNT) AS TOTAL_INFLOW_AMOUNT
FROM WH_INFLOWS A
INNER JOIN PRODUCTS B ON A.PRODUCT = B.ID
INNER JOIN WH_WAREHOUSES D ON A.WAREHOUSE = D.ID
GROUP BY A.WAREHOUSE, D.NAME, B.ID, B.NAME
ORDER BY A.WAREHOUSE;

SELECT B.WAREHOUSE, C.NAME, D.ID, D.NAME, SUM(A.AMOUNT) FROM WH_OUTFLOWS A
INNER JOIN WH_INFLOWS B ON A.INFLOW = B.ID
INNER JOIN WH_WAREHOUSES C ON B.WAREHOUSE = C.ID
INNER JOIN PRODUCTS D ON B.PRODUCT = D.ID
GROUP BY B.WAREHOUSE, C.NAME, D.ID, D.NAME
ORDER BY B.WAREHOUSE;

SELECT A.WAREHOUSE as warehouseId, D.NAME as warehouseName, B.ID as productId, B.NAME as productName, SUM(A.AMOUNT) AS totalInflowAmount FROM WH_INFLOWS A INNER JOIN PRODUCTS B ON A.PRODUCT = B.ID INNER JOIN WH_WAREHOUSES D ON A.WAREHOUSE = D.ID GROUP BY A.WAREHOUSE, D.NAME, B.ID, B.NAME ORDER BY A.WAREHOUSE; 


SELECT SUM(I.amount * I.price) from WH_INFLOWS I
WHERE TO_CHAR(I.LAST_UPD_DATE, 'YYYYMMDD') = '20180329'
AND STATUSKBN=''

SELECT TO_CHAR(I.LAST_UPD_DATE, 'YYYYMM'), SUM(I.amount * I.price) from WH_INFLOWS I
WHERE TO_CHAR(I.LAST_UPD_DATE, 'YYYYMM') = '201803'
GROUP BY TO_CHAR(I.LAST_UPD_DATE, 'YYYYMM');


SELECT SUM(O.amount * O.price) from WH_OUTFLOWS O
WHERE TO_CHAR(O.LAST_UPD_DATE, 'YYYYMMDD') = '20180329'
AND STATUSKBN=''

SELECT SUM(O.amount * O.price) from WH_OUTFLOWS O
WHERE TO_CHAR(O.LAST_UPD_DATE, 'YYYYMM') = '201803'


SELECT SUM(I.amount * I.price) from WH_OUTFLOWS I   WHERE TO_CHAR(I.LAST_UPD_DATE, 'YYYYMMDD') = '20180330'  AND I.STATUSKBN ='2007'

SELECT COALESCE(SUM(I.amount * I.price), 0) from WH_INFLOWS I   WHERE TO_CHAR(I.LAST_UPD_DATE, 'YYYYMM') = '201803'  AND I.STATUSKBN ='2007'

SELECT COALESCE(SUM(I.amount * I.price), 0) from WH_INFLOWS I   WHERE TO_CHAR(I.LAST_UPD_DATE, 'YYYYMM') = '201803'  AND I.STATUSKBN ='2007'